Repository the-boyj/signaling-server, pull requests merged in 2019-01, with the labels that each got.

#26 [#25] Extract each event handlers
  package.json
  src/events/common.js
  src/events/index.js
  src/server.js
  test/events/common-spec.js
  test/events/index-spec.js
Labels: merge needed

#27 [#6] Implement "sice" and "rice" handler
  src/server.js
  test/index-spec.js
Labels: merge needed

#30 Merge issue#25 into issue#6
  .eslintrc
  package.json
  src/events/call.js
  src/events/common.js
  src/events/index.js
  src/events/webrtc.js
  src/server.js
  test/events/call-spec.js
  test/events/common-spec.js
  test/events/index-spec.js
  test/events/webrtc-spec.js
Labels: Answer Needed

#31 Update package.json to version 1.2.0
  package.json
Labels: Answer Needed

#43 Feature#4 Awaken, Accept, Reject
  package-lock.json
  package.json
  src/events/call.js
  test/events/call-spec.js
Labels: answer needed

#51 [#48] Remove flatMap in events/index.js
  src/events/index.js
Labels: review needed

#55 Change version from 1.2.0-5 to 1.2.0
  package.json
Labels: review needed

#60 Add new event 'knock'
  src/events/call.js
  test/events/call-spec.js
Labels: review needed
